### ISSUE TITLE
Support for optional namespaces

### ISSUE THREAD

**Issue by robertjpayne** [mattetti/Weasel-Diesel#23]
Take the below input JSON example:

```
{
  'text': 'This is an awesome text post!',
  'attachment': null
}

{
  'text': 'This is an awesome image post!',
  'attachment': {
    'type': 'image',
    'url': 'myawesomeimage.jpg',
  }
}
```

I'd love for my API to be able to validate against it but allow "attachment" to be completely optional. If attachment is non-nil though I'd want to ensure that type and url are both valid strings and part of the API spec.

Something like this could be really handle allowing it to be null and if so skip over the nested validators.

```
service.params.namespace :attachment, :null => true do |attachment|
  attachment.string :type, :required => true
  attachment.string :url, :required => true
end
```

**Comment by mattetti** [comment]
Agreed

**Comment by pheino** [comment]
I vote for this :+1: 

I also have the use case for accepting an array of name-spaced objects that would be nice to have a min required if present or completely optional

``` JAVASCRIPT
{
  "name" : "My Name",
   "inner-objects" : [ {}, {}, {}]
}

{
  "name" : "My Name"
}
```

**Comment by mattetti** [comment]
Patch welcome ;)  I think we all agree this feature needs to get in, nobody
had time to write it yet tho.

**Comment by mattetti** [comment]
With @kamui PR in, this should solve both @pheino and @robertjpayne problems. I'll close this issue for now, feel free to comment if you think that the provided solution isn't good enough,
