### ISSUE TITLE
Response example is just "#" in generated docs

### ISSUE THREAD

**Issue by drnic** [mattetti/Weasel-Diesel#7]
See https://www.evernote.com/shard/s3/sh/63000003-2a4c-4104-9e28-8cf04e6feb1f/a9437d8d27192d40e115172e0a2e6932

**Comment by mattetti** [comment]
This was a 1.9 bug, I fixed it and added a spec in this commit: 52d9f379b9100192b3244c473403f8abcca73e48
Travis is running the specs on (almost) all rubies so I'm pretty confident that this is now fixed.
